### ISSUE TITLE
Large uploads 'fail' but have succeeded

### ISSUE THREAD

**Issue by platima** [mediacms-io/mediacms#852]
**Setup**

- Hyper-V guest with 8 cores, 12GB RAM
- 7TB SAS RAID1 drive array
- Vanilla Ubuntu 22 Server install
- All updates installed
- Vanilla mediaCMS 3 as per instructions
- Bare minimal config changes to make it useable

I've found many videos, usually ones over 1GB, upload successfully but show as failed, eg:
![image](https://github.com/mediacms-io/mediacms/assets/13729856/1a3cf070-10c2-4e8a-aec1-b1733ec471aa)
Retry does nothing on this, unlike one that has failed a portion of the way through.

I have tried reducing the chunk sizing;
```
CHUNKIZE_VIDEO_DURATION = 60 * 2
VIDEO_CHUNKS_DURATION = 60 * 1
```
But that did not help

I can repro this easily, but am unsure which logs to check.

**Comment by platima** [comment]
Narrowed this down to storage speed.

I moved it from 2Gbps SAN to 6Gbps DAS and the issue went away.

I could push/pull ~100MB/s synchronously on this connection, and the uploads are limited to my 40Mbps / 5MB/s throughput, so must be something to do with latency sensitivity, or maybe checksumming?

**Comment by platima** [comment]
Tested more and it's not storage, but I was close. It's the upload speed.

If I upload to it from a 40Mbps-up connection, I get this issue. If I upload from a 100Mbps-up connection, it's fine. (the server itself is on gigabit enterprise fibre)

Most services in Australia max out at 40Mbps upload, and that's only if they have fibre or REALLY good copper, so this would likely affect many people.

**Comment by platima** [comment]
Okay with even bigger files it still fails on the 100Mbps connection; 
![image](https://github.com/mediacms-io/mediacms/assets/13729856/795facb8-2cac-4f9b-a448-90667c8f3070)

'Retry' does nothing. Chrome console logs;
![image](https://github.com/mediacms-io/mediacms/assets/13729856/5910a7a8-c91b-4ac3-9d93-941e96f33a07)

I can copy and paste the file to another location, so read/write is fine, and having tried three times it keeps doing the same thing.

The files on the server are still in a few parts too;
`root@mediacms:/home/mediacms.io/mediacms/media_files/original/user/admin# ls -Alh *C036*
-rw-r--r-- 1 www-data www-data 2.5G Aug 10 12:33 00_0dwH3A9HG_030e3ca59405463d8d85b8449e84d302.A009_05051034_C036_CC.mov.mkv
-rw-r--r-- 1 www-data www-data 2.5G Aug 10 12:33 01_0dwH3A9HG_030e3ca59405463d8d85b8449e84d302.A009_05051034_C036_CC.mov.mkv
-rw-r--r-- 1 www-data www-data 2.2G Aug 10 12:33 02_0dwH3A9HG_030e3ca59405463d8d85b8449e84d302.A009_05051034_C036_CC.mov.mkv
-rw-r--r-- 1 www-data www-data 2.1G Aug 10 12:33 03_0dwH3A9HG_030e3ca59405463d8d85b8449e84d302.A009_05051034_C036_CC.mov.mkv
-rw-r--r-- 1 www-data www-data 9.0G Aug 10 12:32 030e3ca59405463d8d85b8449e84d302.A009_05051034_C036_CC.mov
`

**Comment by tobocop2** [comment]
I think it's timing out for you. I've successfully uploaded 90 gigabyte files into mediacms and encoded to 240,360,480,and 1080p .h254 

There is currently a hard coded timeout value for the 'short' tasks, and i addressed this in my PR:

https://github.com/mediacms-io/mediacms/pull/856


Also, you can completely eliminate all other timeouts by setting them in your local settings file. For testing, I wanted things to never timeout (don't do this in production).

```python
CELERY_TASK_SOFT_TIME_LIMIT = None
CELERY_TASK_TIME_LIMIT = None
CELERY_SOFT_TIME_LIMIT = None
CELERYD_TASK_SOFT_TIME_LIMIT = None
```

But you can set time limits to something else because the defaults provided by `mediacms` are too short.

**Comment by platima** [comment]
Oh nice one - I'll grab that PR and change the configs. Many thanks!

**Comment by mgogoulos** [comment]
Hi, thanks for the report and for the insightful comments @tobocop2 and @platima . 

I think that the sugestions for uwsgi are valid, there might be something that has to be optimized in this case. And I also believe that the CELERY settings are irrelevant (going to comment on the PR as well), because there's different uses for the word `chunkize` here and we are getting confused: 

- Chrome console logs `Problem finalizing chunks` is related with the fine uploader and Django integration, basically fine uploader (a javascript uploader library) is making chunks of the original file and sending to the Django backend, and something time outs or fails there - this is most probably related with the limits @tobocop2 mentions. As a side note, I want to get rid of fine uploader very soon, because it's deprecated software (despite being great and being used so widely until now), there's a ticket discussion a migration to uppy.io for this

- Celery runs a task that chunkizes the original file, so that it gets to be transcoded by ffmpeg through different available CPU. A file of 1G is split in many chunks, so that different workers can run ffmpeg and transcode each chunk, and finally all chunks are concatenated. @tobocop2 the task that chunkizes the file should be very fast, it's just splitting the file in smaller parts...

As a recap, the problems here seem to be related with the uploading and not post-processing of files. 

On a sidenote, @tobocop2 I am curious to learn what could be a  90 gigabyte file that you've uploaded! I haven't tested the software in so big files, but would be very interested to learn more for this case, what type of videos/workflows you are having here, and what is the infrastructure that processess it. The software is definitely not optimized for that type of videos but I'm happy to read it doesn't fail. One thing I can think of is the command that produces the sprites file (the small images when you hover on the video duration bar), I know that this command fails on a vanilla MediaCMS for videos larger than 1-2 hours, and needs a tweak on the command that produces it (something related to ImageMagick if I remember well). For sure there will be other issues or edge cases here because again the software is not tested on so big files. 

Regards

**Comment by tobocop2** [comment]
@mgogoulos the chunk jobs were all failing for me. You have 300 seconds as the hard coded timeout in the supervisord file and the tasks file. 

The order of precedence is

keyword arguments at command line
arguments in decorator
global arguments. 

Right now there is no way to override the timeout because it's hard coded hence i made https://github.com/mediacms-io/mediacms/pull/856

Regarding the sprites, I overwrote the imagemagick policy.xml file and set it to be like this

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policymap [
  <!ELEMENT policymap (policy)*>
  <!ATTLIST policymap xmlns CDATA #FIXED ''>
  <!ELEMENT policy EMPTY>
  <!ATTLIST policy xmlns CDATA #FIXED '' domain NMTOKEN #REQUIRED
    name NMTOKEN #IMPLIED pattern CDATA #IMPLIED rights NMTOKEN #IMPLIED
    stealth NMTOKEN #IMPLIED value CDATA #IMPLIED>
]>
<!--
  Configure ImageMagick policies.

  Domains include system, delegate, coder, filter, path, or resource.

  Rights include none, read, write, execute and all.  Use | to combine them,
  for example: "read | write" to permit read from, or write to, a path.

  Use a glob expression as a pattern.

  Suppose we do not want users to process MPEG video images:

    <policy domain="delegate" rights="none" pattern="mpeg:decode" />

  Here we do not want users reading images from HTTP:

    <policy domain="coder" rights="none" pattern="HTTP" />

  The /repository file system is restricted to read only.  We use a glob
  expression to match all paths that start with /repository:

    <policy domain="path" rights="read" pattern="/repository/*" />

  Lets prevent users from executing any image filters:

    <policy domain="filter" rights="none" pattern="*" />

  Any large image is cached to disk rather than memory:

    <policy domain="resource" name="area" value="1GP"/>

  Use the default system font unless overwridden by the application:

    <policy domain="system" name="font" value="/usr/share/fonts/favorite.ttf"/>

  Define arguments for the memory, map, area, width, height and disk resources
  with SI prefixes (.e.g 100MB).  In addition, resource policies are maximums
  for each instance of ImageMagick (e.g. policy memory limit 1GB, -limit 2GB
  exceeds policy maximum so memory limit is 1GB).

  Rules are processed in order.  Here we want to restrict ImageMagick to only
  read or write a small subset of proven web-safe image types:

    <policy domain="delegate" rights="none" pattern="*" />
    <policy domain="filter" rights="none" pattern="*" />
    <policy domain="coder" rights="none" pattern="*" />
    <policy domain="coder" rights="read|write" pattern="{GIF,JPEG,PNG,WEBP}" />
-->
<policymap>
  <!-- <policy domain="resource" name="temporary-path" value="/tmp"/> -->
  <policy domain="resource" name="memory" value="1GiB"/>
  <policy domain="resource" name="map" value="30GiB"/>
  <policy domain="resource" name="width" value="16MP"/>
  <policy domain="resource" name="height" value="16MP"/>
  <!-- <policy domain="resource" name="list-length" value="128"/> -->
  <policy domain="resource" name="area" value="40GP"/>
  <policy domain="resource" name="disk" value="100GiB"/>
  <!-- <policy domain="resource" name="file" value="768"/> -->
  <!-- <policy domain="resource" name="thread" value="4"/> -->
  <!-- <policy domain="resource" name="throttle" value="0"/> -->
  <!-- <policy domain="resource" name="time" value="3600"/> -->
  <!-- <policy domain="coder" rights="none" pattern="MVG" /> -->
  <!-- <policy domain="module" rights="none" pattern="{PS,PDF,XPS}" /> -->
  <!-- <policy domain="path" rights="none" pattern="@*" /> -->
  <!-- <policy domain="cache" name="memory-map" value="anonymous"/> -->
  <!-- <policy domain="cache" name="synchronize" value="True"/> -->
  <!-- <policy domain="cache" name="shared-secret" value="passphrase" stealth="true"/>
  <!-- <policy domain="system" name="max-memory-request" value="256MiB"/> -->
  <!-- <policy domain="system" name="shred" value="2"/> -->
  <!-- <policy domain="system" name="precision" value="6"/> -->
  <!-- <policy domain="system" name="font" value="/path/to/font.ttf"/> -->
  <!-- <policy domain="system" name="pixel-cache-memory" value="anonymous"/> -->
  <!-- <policy domain="system" name="shred" value="2"/> -->
  <!-- <policy domain="system" name="precision" value="6"/> -->
  <!-- not needed due to the need to use explicitly by mvg: -->
  <!-- <policy domain="delegate" rights="none" pattern="MVG" /> -->
  <!-- use curl -->
  <policy domain="delegate" rights="none" pattern="URL" />
  <policy domain="delegate" rights="none" pattern="HTTPS" />
  <policy domain="delegate" rights="none" pattern="HTTP" />
  <!-- in order to avoid to get image with password text -->
  <policy domain="path" rights="none" pattern="@*"/>
  <!-- disable ghostscript format types -->
  <policy domain="coder" rights="none" pattern="PS" />
  <policy domain="coder" rights="none" pattern="PS2" />
  <policy domain="coder" rights="none" pattern="PS3" />
  <policy domain="coder" rights="none" pattern="EPS" />
  <policy domain="coder" rights="none" pattern="PDF" />
  <policy domain="coder" rights="none" pattern="XPS" />
</policymap>
```

I'm able to ingest 90 gig files no problem using the basic docker-compose infrastructure you provided with the addition of s3fs added to my docker-compose. Here is my config.


```
version: "3"

# Uses https://github.com/nginx-proxy/acme-companion

services:
  nginx-proxy:
    user: "${UID}:${GID}"
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./deploy/docker/reverse_proxy/nginx:/etc/nginx/conf.d
    restart: always

  acme-companion:
    user: "${UID}:${GID}"
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  migrations:
    user: "${UID}:${GID}"
    image: mediacms/mediacms:latest
    volumes:
      - ./:/home/mediacms.io/mediacms/
    env_file:
      - .env_file  # Load environment variables from the .env_file
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: always
  web:
    user: "${UID}:${GID}"
    build:
      context: .
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    volumes:
      - ./:/home/mediacms.io/mediacms/
      - ./deploy/docker/reverse_proxy/web:/etc/nginx/conf.d
    env_file:
      - .env_file  # Load environment variables from the .env_file
    environment:
      # VIRTUAL_PROTO: uwsgi
      # ENABLE_UWSGI: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
      - s3fs
    restart: always
  celery_beat:
    user: "${UID}:${GID}"
    image: mediacms/mediacms:latest
    volumes:
      - ./:/home/mediacms.io/mediacms/
      - ./deploy/docker/reverse_proxy/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - redis
    restart: always
  celery_worker:
    user: "${UID}:${GID}"
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
      - s3fs
    restart: always
  db:
    user: "${UID}:${GID}"
    image: postgres:13
    volumes:
      - ../postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediacms"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    user: "${UID}:${GID}"
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  s3fs:
    user: "${UID}:${GID}"
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    image: "efrecon/s3fs:1.93"
    restart: always
    env_file:
      - .env_file  # Load environment variables from the .env_file
    environment:
      # uncomment for debug info
      # S3FS_DEBUG: 1
      # S3FS_ARGS: allow_other,use_rrs,umask=0000,nonempty,max_stat_cache_size=100000000,stat_cache_expire=10800,readwrite_timeout=10800,connect_timeout=10800,parallel_count=18,use_cache=/tmp/s3fs
      S3FS_ARGS: allow_other,use_rrs,umask=0000,nonempty,max_stat_cache_size=100000000,readwrite_timeout=10800,connect_timeout=10800,parallel_count=18,use_cache=/tmp/s3fs
      # S3FS_ARGS: allow_other,use_rrs,umask=0000,nonempty
    volumes:
      - ./media_files:/opt/s3fs/bucket:rshared
      - ./s3fs-cache:/tmp/s3fs


  s3fs-cron:
    image: alpine
    command: crond -f
    volumes:
      - ./media_files:/opt/s3fs/bucket:rshared
      - ./s3fs-cache:/tmp/s3fs
      - ./clear_cache.sh:/etc/periodic/hourly/clear_cache
    environment:
      - "SHELL=/bin/sh"
      - "CRON_STR=*/3 * * * * run-parts /etc/periodic/hourly"
    entrypoint:
      - /bin/sh
      - -c
      - |
          echo "$$CRON_STR" > /etc/crontabs/root && exec crond -l 2 -f
    restart: always

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
```

This is just a POC but it works for 90 gig files given all my modifications to the uwsgi, imagemagick, nginx, and django confs. 

This is my local settings file

```
import os

FRONTEND_HOST = 'http://localhost'
PORTAL_NAME = 'MediaCMS'
SECRET_KEY = 'ma!s3^b-cw!f#7s6s0m3*jx77a@riw(7701**(r=ww%w!2+yk2'
POSTGRES_HOST = 'db'
REDIS_LOCATION = "redis://redis:6379/1"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "mediacms",
        "HOST": POSTGRES_HOST,
        "PORT": "5432",
        "USER": "mediacms",
        "PASSWORD": "mediacms",
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_LOCATION,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# CELERY STUFF
BROKER_URL = REDIS_LOCATION
CELERY_RESULT_BACKEND = BROKER_URL

# MP4HLS_COMMAND = "/home/mediacms.io/bento4/bin/mp4hls"

# we can avoid creation of the hls files this way
MP4HLS_COMMAND = 'IGNORE HLS CONVERSION'

DEBUG = True

PORTAL_WORKFLOW = 'private'

UPLOAD_MAX_SIZE = 200 * 1024 * 1024 * 1024  # 214,748,364,800 bytes (200 gigabytes)
REGISTER_ALLOWED = False
MINIMUM_RESOLUTIONS_TO_ENCODE = [720]
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CELERY_TASK_SOFT_TIME_LIMIT = None
CELERY_TASK_TIME_LIMIT = None
CELERY_SOFT_TIME_LIMIT = None
CELERYD_TASK_SOFT_TIME_LIMIT = None
EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'
MEDIA_URL = 'SOME+CLOUD_FRONT_URL'

```

Note i disabled the hls conversion because i don't need it.

**Comment by platima** [comment]
Always happy to help, and thanks for commenting on this ticket. Looking forward to a better uploader then :P

**Comment by KyleMaas** [comment]
I'm quite regularly running into this issue as well.  Thanks for the suggestions, everyone!  Will try some of this and see if it helps.  It would be great if some of this information was put into the admin documentation.

**Comment by mgogoulos** [comment]
This ticket stays open until there is some info of it moved to the admin docs. 
@tobocop2 I'm wondering which parts could go into the main repository, to optimize the default timeouts/settings. 

Next, how is s3fs performance in playing these videos? Any observations? 

And also out of curiosity, what are these 90GB files, what sector are you working on?

**Comment by tobocop2** [comment]
@mgogoulos 

I completely abandoned s3fs for my needs. It's unsuitable for large files and i ultimately devised a solution that simply uses aws s3 sync via a cronjob. I am going to migrate this to use aws datasync eventually. 

The 90 gig files are are broadcast media files (mxf format, i had to add my own mimetype for them to work with mediacms). 

For playback, I'm using the MEDIA_URL setting in django and serving all of my files from s3 over cloudfront. This is breaking static assets in some places but I am ok with that for the time being. I see an existing PR here: 
https://github.com/mediacms-io/mediacms/pull/869/files

which should fix that issue for me. 

In order to actually support the throughput and scale I needed, I had to deploy mediacms in two configurations:

A) ingest mode (EC2 + EBS (GP3 max IOPS and max throughput) + local redis + shared RDS postgres
B) basic  mode (ECS + EFS + Elasticache + RDS) 

I have successfully ingested over 60 terrabytes of media through mediacms with some modifications to the deployment configurations and my own aws infrastructure code using terraform. Thank you as well as all of the contributors to this project @mgogoulos

**Comment by mgogoulos** [comment]
> mxf format

thanks for the very interesting information and insights, on the usage of s3fs, customizations and your use case. I'll try to review the PRs and merge them soon.

**Comment by KyleMaas** [comment]
I'd like to note that I have not found any of the suggestions here to work for me.  I still get this problem when large files are uploaded.  The uploader will show the upload as failed, the file will not appear in the user's media list, but then a while later the file will show up anyway.  Have not had the time to trace it down.  I've just told users who upload huge files that it's a known issue, and if it says failed it probably worked so they will need to just check back later.

**Comment by crossany** [comment]
Yes, I found this error, maybe the iPhone's new video recording format. I switched from an iPhone 11 to an iPhone 17e. The iOS version has also been upgraded from 17 to 26. I found the details of my two video files. I found the recode display "Timed Metadata, APAC, MPEG-4 AAC, H.264," but the old videos are not included in the APAC format.
So I adjust my camera settings in the iPhone Settings. I changed Record Sound from Spatial Audio to Stereo. The issue has been fixed.
